### ISSUE TITLE
SegFault

### ISSUE THREAD

**Issue by ryanford** [LinguaLeo/lua-sass#1]
Trying to run on Ubuntu Xenial. Compiled OK (no errors), includes in lua with both functions intact. When I try to run `sass.compile(".a { color: red }")` it segfaults. 

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> sass = require('sass')
> print(sass.compile(".a { color: red }"))
*** Error in `lua': free(): invalid pointer: 0x0000000001a6c028 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f5f9edfe7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f5f9ee0737a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f5f9ee0b53c]
/usr/lib/x86_64-linux-gnu/libsass.so.0(_ZN4Sass7ContextD2Ev+0x4c)[0x7f5f9e35423c]
/usr/lib/x86_64-linux-gnu/libsass.so.0(_ZN4Sass12Data_ContextD0Ev+0x9)[0x7f5f9e354619]
/usr/lib/x86_64-linux-gnu/libsass.so.0(sass_delete_compiler+0x18)[0x7f5f9e428468]
/usr/lib/x86_64-linux-gnu/libsass.so.0(+0x18f4a9)[0x7f5f9e4284a9]
/usr/local/openresty/luajit/lib/lua/5.1/sass.so(+0xf5b)[0x7f5f9e683f5b]
lua[0x4080d8]
lua[0x4116d2]
lua[0x40852d]
lua[0x40782b]
lua[0x40868b]
lua(lua_pcall+0x56)[0x405d26]
lua[0x403ecc]
lua[0x4041cd]
lua[0x4048c5]
lua[0x4080d8]
lua[0x4084e4]
lua[0x40782b]
lua[0x40868b]
lua(lua_cpcall+0x35)[0x405db5]
lua(main+0x44)[0x403b94]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f5f9eda7830]
lua(_start+0x29)[0x403c19]
======= Memory map: ========
00400000-0042a000 r-xp 00000000 08:06 272503                             /usr/local/bin/lua
00629000-0062a000 r--p 00029000 08:06 272503                             /usr/local/bin/lua
0062a000-0062b000 rw-p 0002a000 08:06 272503                             /usr/local/bin/lua
01a23000-01a86000 rw-p 00000000 00:00 0                                  [heap]
7f5f98000000-7f5f98021000 rw-p 00000000 00:00 0 
7f5f98021000-7f5f9c000000 ---p 00000000 00:00 0 
7f5f9dcfa000-7f5f9dd10000 r-xp 00000000 08:06 2098469                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f5f9dd10000-7f5f9df0f000 ---p 00016000 08:06 2098469                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f5f9df0f000-7f5f9df10000 r--p 00015000 08:06 2098469                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f5f9df10000-7f5f9df11000 rw-p 00016000 08:06 2098469                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f5f9df11000-7f5f9e08b000 r-xp 00000000 08:06 262199                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f5f9e08b000-7f5f9e28a000 ---p 0017a000 08:06 262199                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f5f9e28a000-7f5f9e294000 r--p 00179000 08:06 262199                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f5f9e294000-7f5f9e296000 rw-p 00183000 08:06 262199                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f5f9e296000-7f5f9e299000 rw-p 00000000 00:00 0 
7f5f9e299000-7f5f9e470000 r-xp 00000000 08:06 265788                     /usr/lib/x86_64-linux-gnu/libsass.so.0.0.9
7f5f9e470000-7f5f9e66f000 ---p 001d7000 08:06 265788                     /usr/lib/x86_64-linux-gnu/libsass.so.0.0.9
7f5f9e66f000-7f5f9e679000 r--p 001d6000 08:06 265788                     /usr/lib/x86_64-linux-gnu/libsass.so.0.0.9
7f5f9e679000-7f5f9e67a000 rw-p 001e0000 08:06 265788                     /usr/lib/x86_64-linux-gnu/libsass.so.0.0.9
7f5f9e67a000-7f5f9e683000 rw-p 00000000 00:00 0 
7f5f9e683000-7f5f9e685000 r-xp 00000000 08:06 1967940                    /usr/local/openresty/luajit/lib/lua/5.1/sass.so
7f5f9e685000-7f5f9e884000 ---p 00002000 08:06 1967940                    /usr/local/openresty/luajit/lib/lua/5.1/sass.so
7f5f9e884000-7f5f9e885000 r--p 00001000 08:06 1967940                    /usr/local/openresty/luajit/lib/lua/5.1/sass.so
7f5f9e885000-7f5f9e886000 rw-p 00002000 08:06 1967940                    /usr/local/openresty/luajit/lib/lua/5.1/sass.so
7f5f9e886000-7f5f9eb5e000 r--p 00000000 08:06 262726                     /usr/lib/locale/locale-archive
7f5f9eb5e000-7f5f9eb83000 r-xp 00000000 08:06 2101855                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f5f9eb83000-7f5f9ed82000 ---p 00025000 08:06 2101855                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f5f9ed82000-7f5f9ed86000 r--p 00024000 08:06 2101855                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f5f9ed86000-7f5f9ed87000 rw-p 00028000 08:06 2101855                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f5f9ed87000-7f5f9ef47000 r-xp 00000000 08:06 2103426                    /lib/x86_64-linux-gnu/libc-2.23.so
7f5f9ef47000-7f5f9f147000 ---p 001c0000 08:06 2103426                    /lib/x86_64-linux-gnu/libc-2.23.so
7f5f9f147000-7f5f9f14b000 r--p 001c0000 08:06 2103426                    /lib/x86_64-linux-gnu/libc-2.23.so
7f5f9f14b000-7f5f9f14d000 rw-p 001c4000 08:06 2103426                    /lib/x86_64-linux-gnu/libc-2.23.so
7f5f9f14d000-7f5f9f151000 rw-p 00000000 00:00 0 
7f5f9f151000-7f5f9f18e000 r-xp 00000000 08:06 2101834                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7f5f9f18e000-7f5f9f38e000 ---p 0003d000 08:06 2101834                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7f5f9f38e000-7f5f9f390000 r--p 0003d000 08:06 2101834                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7f5f9f390000-7f5f9f396000 rw-p 0003f000 08:06 2101834                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7f5f9f396000-7f5f9f397000 rw-p 00000000 00:00 0 
7f5f9f397000-7f5f9f39a000 r-xp 00000000 08:06 2103415                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f5f9f39a000-7f5f9f599000 ---p 00003000 08:06 2103415                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f5f9f599000-7f5f9f59a000 r--p 00002000 08:06 2103415                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f5f9f59a000-7f5f9f59b000 rw-p 00003000 08:06 2103415                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f5f9f59b000-7f5f9f6a3000 r-xp 00000000 08:06 2103421                    /lib/x86_64-linux-gnu/libm-2.23.so
7f5f9f6a3000-7f5f9f8a2000 ---p 00108000 08:06 2103421                    /lib/x86_64-linux-gnu/libm-2.23.so
7f5f9f8a2000-7f5f9f8a3000 r--p 00107000 08:06 2103421                    /lib/x86_64-linux-gnu/libm-2.23.so
7f5f9f8a3000-7f5f9f8a4000 rw-p 00108000 08:06 2103421                    /lib/x86_64-linux-gnu/libm-2.23.so
7f5f9f8a4000-7f5f9f8ca000 r-xp 00000000 08:06 2103404                    /lib/x86_64-linux-gnu/ld-2.23.so
7f5f9faa9000-7f5f9faad000 rw-p 00000000 00:00 0 
7f5f9fabf000-7f5f9fac0000 rw-p 00000000 00:00 0 
7f5f9fac0000-7f5f9fac7000 r--s 00000000 08:06 400228                     /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f5f9fac7000-7f5f9fac9000 rw-p 00000000 00:00 0 
7f5f9fac9000-7f5f9faca000 r--p 00025000 08:06 2103404                    /lib/x86_64-linux-gnu/ld-2.23.so
7f5f9faca000-7f5f9facb000 rw-p 00026000 08:06 2103404                    /lib/x86_64-linux-gnu/ld-2.23.so
7f5f9facb000-7f5f9facc000 rw-p 00000000 00:00 0 
7ffc8ae81000-7ffc8aea2000 rw-p 00000000 00:00 0                          [stack]
7ffc8af8e000-7ffc8af90000 r--p 00000000 00:00 0                          [vvar]
7ffc8af90000-7ffc8af92000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

**Comment by craigbarnes** [comment]
This repo is a fork of my outdated Lua bindings for an old version of libsass, back before they repeatedly broke API/ABI compat and I gave up updating it. To get the bindings working again would probably involve a from-scratch rewrite at this point.

**Comment by ryanford** [comment]
Would you happen to know the last compatible release of libsass that worked before the project was abandoned?

**Comment by craigbarnes** [comment]
> Would you happen to know the last compatible release of libsass that worked before the project was abandoned?

Not from memory, but the last time the bindings were updated for an API break seems to have been on 22 Jan 2015 (in commit 8698cde08da13758d8b1df2aab57946903664a65). libsass commits from around the same time should work.

I'm not sure if things have changed or not since, but the notions of "releases" and "API/ABI stability" were alien concepts to the libsass developers back then.

**Comment by craigbarnes** [comment]
When I try to compile with libsass 3.4.7 on Arch, I just get the error:

> sass.c:20:10: fatal error: sass_context.h: No such file or directory

What version of libsass are you compiling against? Are you just using the makefile to build?

**Comment by ryanford-frontend** [comment]
Well, I used the one from apt so...
```text
libsass-dev/xenial,now 3.3.4-1 amd64 [installed]
  C/C++ port of the Sass CSS precompiler - development headers

libsass0/xenial,now 3.3.4-1 amd64 [installed]
```

**Comment by craigbarnes** [comment]
@ryanford-frontend 

I've just pushed my old lua-sass repo to https://github.com/craigbarnes/lua-sass and [fixed](https://github.com/craigbarnes/lua-sass/commit/85ec97368d40b852ffda6e640d1545f9943a7385) this bug. I'll probably also add Lua 5.3 support at some point.
